language: php

sudo: false

php:
  - 7.1
  - 7.2
  - nightly

cache:
  directories:
  - "$HOME/.composer/cache/files"

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

before_script:
    - travis_retry composer self-update
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --no-suggest --prefer-source

script:
    - vendor/bin/phpunit
    - vendor/bin/phpstan analyse
