dist: bionic
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
  - "$HOME/.composer/cache/files"

matrix:
  allow_failures:
    - php: nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer update --no-interaction --no-suggest --prefer-source

script: composer test
